spring.application.name=GharSeva

# SERVER CONFIG
server.port=${PORT:8080}

# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/gharsevadb
spring.datasource.username=postgres
spring.datasource.password=root

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT CONFIG
app.jwt.secret=IAmGeekyHimAndThisIsMyJWTSecret
app.jwt.expirationMinutes=60