# PORT=8080
server.port=${PORT:8080}
server.forward-headers-strategy=framework
spring.profiles.active=prod

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expirationMinutes=${APP_JWT_EXPIRATIONMINUTES}

#spring.profiles.active=dev

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html