PORT=8080

SPRING_PROFILES_ACTIVE=prod

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expirationMinutes=${APP_JWT_EXPIRATIONMINUTES}

# spring.profiles.active=dev